### ISSUE TITLE
Epic: finish courtbot

### ISSUE THREAD

**Issue by groovecoder** [codefortulsa/courtbot-python#1]
Based on hack night's session, we came up with these major "phases" of building the new courtbot system:

* [x] Set up Amazon Lex with Twilio and Lambda functions to get Year, County, and Case from the end user.
* [ ] Add an API call: `GET https://courtbot.com/case?year=&county=&case=` endpoint finds the case, and responds with the full case object, including the arraignment date.
* [ ] Call the `GET /case?` endpoint from the lambda function, and then ask the user to confirm reminders.
* [ ] Add an API call: `POST https://courtbot.com/reminders` with the case, phone #, and date. `courtbot.com` creates all reminders for the case.
* [ ] When the user confirms the reminders, the lambda function invokes the `POST /reminders` endpoint
* [ ] Add cron job to `courtbot.com` that checks for un-sent reminders and sends them.

![IMG_0185](https://user-images.githubusercontent.com/71928/60665513-467e2d00-9e2a-11e9-9216-14d06a17f382.JPG)
